name = "VisClaw"
uuid = "d5c85fe6-8620-4d3a-96f0-ac478d4f5d38"
authors = ["Takuya Miyashita <miyashita@hydrocoast.jp>"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
